name: image build

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/pr-docker.yml'
    - 'Dockerfile'
    - 'src/**'
    - 'benches/**'
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/pr-docker.yml'
    - 'Dockerfile'

  # For manually triggering workflow
  workflow_dispatch:

jobs:
  start-runner:
    name: ec2-start
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Start EC2 runner
      id: start-ec2-runner
      uses: machulav/ec2-github-runner@v2
      with:
        mode: start
        github-token: ${{ secrets.PAT }}
        ec2-image-id: ami-05a99cf0eb100c377
        ec2-instance-type: c5.4xlarge
        subnet-id: subnet-59743123
        security-group-id: sg-9ec32bfe
  build-and-push-images:
    needs:
    - start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build nexmark-server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/risingwavelabs/nexmark-bench
  stop-runner:
    name: ec2-stop
    needs:
    - start-runner
    - build-and-push-images
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Stop EC2 runner A
      uses: machulav/ec2-github-runner@v2
      with:
        mode: stop
        github-token: ${{ secrets.PAT }}
        label: ${{ needs.start-runner.outputs.label }}
        ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
      if: ${{ always() }}