name: image build

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/pr-docker.yml'
    - 'Dockerfile'
    - 'src/**'
    - 'benches/**'
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/pr-docker.yml'
    - 'Dockerfile'

  # For manually triggering workflow
  workflow_dispatch:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build nexmark-server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/risingwavelabs/nexmark-bench
